In [14]:
import numpy as np

In [15]:
l = [1, 2, 3, 4]
np_arr = np.array(l)
print(np_arr, type(np_arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [16]:
#shape attribute returns numner of element in each dimension
np_arr.shape

(4,)

In [17]:
l = list(range(0,12))
np_arr = np.array(l)
print(np_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [19]:
l = list(range(0,12))
np_arr = np.array(l)
np_arr.shape

(12,)

In [20]:
np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
np_arr.reshape((12,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [22]:
np_arr.reshape((2,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [23]:
np_arr_3d = np_arr.reshape((2,2,3))
np_arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
#ndim attribute provides the number of dimension of numpy array
np_arr_3d.ndim

3

In [25]:
np_arr_2d = np_arr.reshape((3,4))
np_arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
 
np_arr_2d[2][1]

9

In [27]:
np_arr_2d[2]# aaccess dim 1 elementr and that is arryay of index 2

array([ 8,  9, 10, 11])

In [28]:
np_arr_2d[2,1]

9

In [29]:
np_arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
np_arr_2d[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np_arr_2d[1:2:]

array([[4, 5, 6, 7]])